name: MovieCatalog_Exam2026

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore MovieCatalogTests.slnx

    - name: Build
      run: dotnet build ExamMovieCatalog_2026.slnx --no-restore

    - name: Test
      run: dotnet test ExamMovieCatalog_2026.slnx --no-build --verbosity normal
